### PR TITLE
Typescript score reporting

### PR DESCRIPTION
**Pull request by slmnio**
New score reporting system, using Typescript on the server

### Main

- [x] Member of team submits match data for score report
- [x] Member of opponent approves score report
- [ ] Member of opponent denies score report
  - What does denying by opponent do?
    - Full delete?
    - Replace original submission data?
    - If sent back to original team, should it compare the two?
    - Lock any future attempts at approving?
    - Alert staff?
- [x] Staff member approves score report
- [ ] Staff member denies score report
  - What does staff denial look like?
    - Full delete?
    - Restriction of the match from being reported?
    - Staff can edit the match directly anyway
    - Give staff the ability to use that data to start with then submit?
      - This could be on the match editor anyway if there's a pending score report

- [x] Server needs to update match data with the submission's details after the approvals are done

### Logging

- [ ] Score report submission message sent to in-progress score report channel for staff after initial submission
- [x] Score report submission message sent to in-progress score report channel for staff after both teams have approved
- [ ] Finalised score report submission message sent to finalised score reporting channel

### Messaging

- [ ] Message sent to opponent staff/captains to approve/deny score report
  - [ ] Need some sort of handler to receive data from Discord
- [ ] Confirmation message sent to {person} after opponent has approved

Messages could be sent to team channels with option to ping
- Score report needs approving
- Score report has been approved by opponent
- Score report has been approved by staff
- New match has been created with this team
- (additional messages for start times etc)

### CODE REVIEW

**Comment by slmnio** [comment]
@zusorio you'll know more about how to fix this build failure with the pnpm monorepo

**Comment by zusorio** [comment]
I was going to fix this but then webstorm didn't start, I think you just have to delete and recreate the lockfile

**Comment by slmnio** [comment]
Why have the lint/run actions stopped running

**Comment by slmnio** [comment]
Almost ready to start beta testing. 

Done:
- Staff force approve (approve after submission without opponent approval when it is normally required)
- Captains notification pings
- Staff notification pings
- Score report channel messages
- Bunch of UI stuff to show when matches are ready for score reporting on the schedule, and the whole flow on the score reporting view with all of its optional trees.

Need to do before testing:
- [ ] Staff deny/delete
- [ ] Beta warning message & explanations
- [ ] Server validation for map data entries (currently generated on client and sent up - is this so bad?)

Post-testing goals:
- [ ] Discord one click approvals with buttons
- [ ] Deeper validation on what's required/not required when submitting map data
- [ ] Discord DMs instead of (or as well as) team pings
- [ ] Message or actions if a team denies
- [ ] Using this flow for match start time changes
- [ ] Player stuff: team trades when it detects add & removal at the same time (maybe)
- [ ] Player stuff: dealing with brand new players being added

**Pull request merged**
